project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "[Kinlan M.G. Jan]{.myname}"
  page-footer:
    left:  "2026 Kinlan M.G. Jan"
    center: "[{{< fa brands github >}} Source Code](https://github.com/KMGJan/KMGJan.github.io){target=_blank}"
    right: This website is built with [Quarto](https://quarto.org/){target=_blank}. 
  navbar:
    background: "#111111"
    pinned: true
    logo: img/image.png
    align: center
    collapse-level: 1
    right:
      - text: "{{< fa graduation-cap >}} PhD project"
        href: PhD/index.qmd
      - text: "{{< fa paperclip >}}Publications"
        href: Publications/index.qmd
      - text: "{{< fa address-card >}} Curriculum Vitae"
        menu:
        - text: "English 🇬🇧"
          href: CV/CV_english.qmd
        - text: "Français 🇫🇷"
          href: CV/CV_french.qmd
      - text: "{{< fa brands github >}}"
        href: "https://github.com/KMGJan"
        target: "_blank"
      - text: "{{< fa paper-plane >}}"
        href: mailto:kinlan.jan@hotmail.ch
        
format:
  html:
    theme: [cosmo, theme-light.scss]
    css: styles.css
    toc: false
    mainfont: Jost
execute:
  freeze: auto