---
title: Curriculum Vitae
lang: en
format: 
  html:
    toc: true
    toc-title: Curriculum Vitae
    toc-location: right
    toc-depth: 2
    toc-expand: true
    date: last-modified
    date-format: "MMMM YYYY"
    author:
    - name: Kinlan M.G. Jan
      orcid: 0000-0002-5579-0017
      affiliations:
      #- Queen's University Belfast, Belfast, Northern Ireland
  pdf:
    author: Kinlan M.G. Jan
    pdf-engine: weasyprint
css: CV_english.css
format-links: [pdf]
---
```{r}
#| echo: false
#| message: false
#| warning: false

library(scholar)

scholar_id <- "Vf6gRpIAAAAJ"
profile <- get_profile(scholar_id)

h_index <- profile$h_index
i10_index <- profile$i10_index
total_citations <- profile$total_cites
retrieval_date <- format(Sys.Date(), "%d/%m/%Y")
```

::: {.print-only .contact-block}
[kinlan.jan@hotmail.ch](mailto:kinlan.jan@hotmail.ch){.email}
[0000-0002-5579-0017](https://orcid.org/0000-0002-5579-0017){.orcid}
[KMGJan](https://github.com/KMGJan){.github}
:::



## Education 

[[[**PhD**]{.educationtitle} **in Marine Biology**]{.edu} [**Stockholm, Sweden**]{.cvlocation}]{.cvcontainer} <br>
[Stockholm University [*September 2021 --- January 2026*]{.cvdate}]{.cvcontainer}<br>
Thesis title: [Resolving diversity and ecosystem functioning in a changing sea](https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-249847){.course target=_blank}

[[[**MSc**]{.educationtitle} **in Marine Biology**]{.edu} [**Stockholm, Sweden**]{.cvlocation}]{.cvcontainer} <br>
[Stockholm University [*August 2019 --- June 2021*]{.cvdate}]{.cvcontainer}<br>
Master project title: [Copepod feeding preferences along the Baltic Sea environmental gradients]{.course}

[[[**BSc**]{.educationtitle} **in Biology**]{.edu} [**Neuchâtel, Switzerland**]{.cvlocation}]{.cvcontainer} <br>
[The University of Neuchâtel [*September 2017 --- June 2019*]{.cvdate}]{.cvcontainer}

<!--
## Academic positions

[**Research Fellow** in Isotope Ecology and Mesopelagic Prey Fields [**Belfast, United Kingdom**]{.cvlocation}]{.cvcontainer} <br>
[Queen's University Belfast, School of Biological Sciences [*May 2026 --- Present*]{.cvdate}]{.cvcontainer}
--->

## Teaching

[**Stockholm University** [**Stockholm, Sweden**]{.cvlocation}]{.cvcontainer} <br>
[Marine ecosystem dynamics, [MSc]{.educationtitle} course]{.edu} [*2021 --- 2025*]{.cvdate} <br>
[Marine ecology, [BSc]{.educationtitle} course]{.edu} [*2022*]{.cvdate}

[**The University of Neuchâtel** [**Neuchâtel, Switzerland**]{.cvlocation}]{.cvcontainer} <br> [From molecules to cells, [BSc]{.educationtitle} course]{.edu} [*2018 --- 2019*]{.cvdate}

## Experience

**Sampling** <br>
<!--MOSAIC sampling cruise in the Atlantic Ocean [July 2026]{.cvdate} <br> --->
Herring Larvae Survey in the Stockholm archipelago [2023 --- 2024]{.cvdate} <br>
Sprat Acoustic Survey in the Baltic Sea [2022 --- 2023]{.cvdate} <br>
Plankton monitoring survey in the Baltic Sea [September 2020]{.cvdate}

**DNA Metabarcoding** <br>
*Laboratory*: DNA extraction, PCR amplification, library preparation, gel electrophoresis <br>
*Bioinformatics*: Sequence processing and taxonomic assignment

**Statistical analysis and reproducible workflows** <br>
Data wrangling, visualization and reporting in R <br>
Version control using Git

**Food web and ecosystem modelling** <br>
Trophic network analysis <br>
Integration of biomass, environmental, and metabarcoding datasets

## Awards and grants

Elisabeth och Herman Rhodin Memorial Foundation [*2024*]{.cvdate} <br>
ICES travel funds for early career scientists [*2024*]{.cvdate} <br>
BalticWaters Scholarship program for early career researchers [*2024*]{.cvdate} <br>
Dryssen Award for best Master's Theses in Marine Sciences [*2021*]{.cvdate}


## Publications

**h-index:** `r h_index` | **i10-index:** `r i10_index` | **Total citations:** `r total_citations` [(Google Scholar, `r retrieval_date`)]{.cvdate}

**First author publications**<br>
Jan KMG, Hentati-Sundberg J, Larson N, Winder M. 2025. [*Limited resource use overlaps among small pelagic fish species in the central Baltic Sea*]{.pubtitle}. ICES Journal of Marine Science 82:9, fsaf122. doi: [10.1093/icesjms/fsaf122](https://doi.org/10.1093/icesjms/fsaf122){.doi target=_blank}

Jan KMG, Serandour B, Walve J, Winder M. 2024. [*Plankton blooms over the annual cycle shape trophic interactions under climate change*]{.pubtitle}. Limnology and Oceanography Letters 9:3, 209-218. doi: [10.1002/lol2.10385](https://doi.org/10.1002/lol2.10385){.doi target=_blank}

Novotny A\*, Jan KMG\*, Dierking J, Winder M. 2022. [*Niche partitioning between planktivorous fish in the pelagic Baltic Sea assessed by DNA metabarcoding, qPCR and microscopy*]{.pubtitle}. Scientific Reports 12, 10952. doi: [10.1038/s41598-022-15116-7](https://doi.org/10.1038/s41598-022-15116-7){.doi target=_blank}
<br>
\* *Shared first authors*

**Co-authored publications**<br>
Hanström N, Jan KMG, Serandour B, Xu T, Winder M. 2025. [*Diet composition and environmental niche drive parasitic Syndiniales interactions with crustacean zooplankton*]{.pubtitle}. ISME Communications, ycaf248. doi: [10.1093/ismeco/ycaf248](https://doi.org/10.1093/ismeco/ycaf248){.doi target=_blank}

Serandour B, Blenckner T, Jan KMG, Leroy B, Ramiro-Sánchez B, Campbell E, Winder M. 2024. [*Projections of spatial distributions of suitable environmental conditions for key Baltic Sea zooplankton species*]{.pubtitle}. Limnology and Oceanography 69:12, 2801-2814. doi: [10.1002/lno.12705](https://doi.org/10.1002/lno.12705){.doi target=_blank}

Novotny A, Serandour B, Kortsch S, Gauzens B, Jan KMG, Winder M. 2023. [*DNA metabarcoding highlights cyanobacteria as the main source of primary production in a pelagic food web model*]{.pubtitle}. Science advances 9:17, eadg1096. doi: [10.1126/sciadv.adg1096](https://doi.org/10.1126/sciadv.adg1096){.doi target=_blank}

Serandour B, Jan KMG, Novotny A, Winder M. 2023. [*Opportunisitic vs selective feeding strategies of zooplankton under changing environmental conditions*]{.pubtitle}. Journal of Plankton Research 45:2, 389-403. doi: [10.1093/plankt/fbad007](https://doi.org/10.1093/plankt/fbad007){.doi target=_blank}

## Conferences

Presented 9 contributions (6 oral presentations, 3 posters) at international and national conferences, including:

- Ocean Sciences Meeting (2026, Talk)
- ICES Annual Science Conference (2024, Poster)
- Baltic Sea Science Congress (2023, Talk)

## Commissions of trust

Chair of the PhD council [*2023*]{.cvdate} <br>
Vice-chair of the PhD council [*2022*]{.cvdate} <br>
Technical assistance with PhD hybrid defenses [*2022 --- 2023*]{.cvdate}

## Academic services

**Session co-chair**, Ocean Sciences Meeting (2026) <br>
Session: [Environmental DNA and ‘Omics Approaches to Unraveling Marine Biodiversity, Species Interactions, and Ecosystem Change]{.course}

**Ad-hoc reviews** <br>
Deep Sea Research Part II: Topical Studies in Oceanography,
Limnology and Oceanography Letters,
Marine Ecology Progress Series,
Molecular Ecology
