---
title: Curriculum Vitae
lang: fr
format: 
  html:
    toc: true
    toc-title: Curriculum Vitae
    toc-location: right
    toc-depth: 2
    toc-expand: true
    date: last-modified
    date-format: "MMMM YYYY"
    author:
    - name: Kinlan M.G. Jan
      orcid: 0000-0002-5579-0017
      affiliations:
      - Stockholm University, Stockholm, Sweden
  pdf:
    author: Kinlan M.G. Jan
    pdf-engine: weasyprint
css: CV_french.css
format-links: [pdf]
---


::: {.print-only .contact-block}
**Doctorant en biologie marine** <br>
Department of Ecology, Environment and Plant Sciences, Stockholm University

[kinlan.jan@su.se](mailto:kinlan.jan@su.se){.email}
[0000-0002-5579-0017](https://orcid.org/0000-0002-5579-0017){.orcid}
[KMGJan](https://github.com/KMGJan){.github}
:::


## Éducation 

[[[**PhD**]{.educationtitle} **en biologie marine**]{.edu} [**Stockholm, Suède**]{.cvlocation}]{.cvcontainer} <br>
[Stockholm University [*Septembre 2021 --- Présent*]{.cvdate}]{.cvcontainer}

[Titre préliminaire de thèse :]{.subedu} [Implication of plankton-fish interactions and dynamics for the Baltic Sea food webs]{.course}
<br>
[Date de défense prévue :]{.subedu} [Janvier 2026]{.course}
<br>
[[Cours : ]{.subedu}
[- Introduction to Stock Assessment, ICES, Danemark]{.courseList1} [2024]{.coursedate} <br>
[- Scientific Writing, BioResearch School, Stockholm University, Suède]{.courseList} [2023 -- 2024]{.coursedate} <br>
[- RaukR - Advanced R for Bioinformatics, NBIS, Suède]{.courseList} [2023]{.coursedate} <br>
[- Introduction to Bioinformatics using NGS data, NBIS, Suède]{.courseList} [2022]{.coursedate} <br>
[- Fish and Fisheries Ecology, SLU, Suède]{.courseList} [2021]{.coursedate}]{.no-print}

[[[**MSc**]{.educationtitle} **en biologie marine**]{.edu} [**Stockholm, Suède**]{.cvlocation}]{.cvcontainer} <br>
[Stockholm University [*Août 2019 --- Juin 2021*]{.cvdate}]{.cvcontainer}

[Titre de projet de Master :]{.subedu} [Copepod feeding preferences along the Baltic Sea environmental gradients]{.course}
<br>
[[Cours:]{.subedu}
[- Baltic Sea Ecosystem: Applications, Modeling and Management]{.courseList1} [2020]{.coursedate} <br>
[- Management of Aquatic Resources in the Tropics]{.courseList} [2020]{.coursedate} <br>
[- Applied Marine Conservation Ecology]{.courseList} [2019-2020]{.coursedate} <br>
[- Biological Statistics]{.courseList} [2019]{.coursedate} <br>
[- Marine Ecosystem Dynamics]{.courseList} [2019]{.coursedate} ]{.no-print}

[[[**BSc**]{.educationtitle} **en biologie**]{.edu} [**Neuchâtel, Suisse**]{.cvlocation}]{.cvcontainer} <br>
[Université de Neuchâtel [*Septembre 2017 --- Juin 2019*]{.cvdate}]{.cvcontainer}


## Enseignement

[**Stockholm University** [**Stockholm, Suède**]{.cvlocation}]{.cvcontainer} <br>
[Marine ecosystem dynamics, Niveau [MSc]{.educationtitle} ]{.edu} [*2021 --- 2025*]{.cvdate} <br>
[Marine ecology, Niveau [BSc]{.educationtitle} ]{.edu} [*2022*]{.cvdate}

[**Université de Neuchâtel** [**Neuchâtel, Suisse**]{.cvlocation}]{.cvcontainer} <br> [Des molécules aux cellules, Niveau [BSc]{.educationtitle}]{.edu} [*2018 --- 2019*]{.cvdate}


## Mandats de confiance

[Président du conseil doctoral]{.edu} [*2023*]{.cvdate} <br>
[Vice-président du conseil doctoral]{.edu} [*2022*]{.cvdate} <br>
[Assistant technique lors des soutenances hybrides de doctorat]{.edu} [*2022 --- 2023*]{.cvdate}


## Prix et bourses

Elisabeth och Herman Rhodin Memorial Foundation [*2024*]{.cvdate} <br> [*Bourse de voyage*]{.edu}

ICES travel funds for early career scientists [*2024*]{.cvdate} <br> [*Bourse de voyage*]{.edu}

BalticWaters Scholarship program for early career researchers [*2024*]{.cvdate} <br> [*Competition between forage fish in the open waters of the Baltic Sea*]{.edu}

Dryssen Award for best Master's Theses in Marine Sciences [*2021*]{.cvdate} <br> [*Copepod feeding preferences along the Baltic Sea environmental gradients - an assessment of zooplankton interactions using DNA metabarcoding*]{.edu}


## Expérience

### Travail de terrain

**Échantillonnage de poissons** <br>
[Campagne sur les larves de hareng]{.edu} [2023 --- 2024]{.cvdate} <br>
[Campagne acoustique sur le sprat en mer Baltique]{.edu} [2022 --- 2023]{.cvdate}

**Échantillonnage de plancton** <br>
[Campagne de suivi en mer Baltique]{.edu} [Septembre 2020]{.cvdate}

### Travail en laboratoire

**Métabarcoding de l'ADN** <br>
[Préparation de librairies | Extraction d’ADN | PCR | Électrophorèse sur gel]{.pubtitle}

**Identification du zooplancton** <br>
[Microscopie]{.pubtitle}


## Publications

***Jan KMG***, Hentati-Sundberg J, Larson N, Winder M. 2025. [*Limited resource use overlaps among small pelagic fish species in the central Baltic Sea*]{.pubtitle}. ICES Journal of Marine Science. doi:[10.1093/icesjms/fsaf122](https://doi.org/10.1093/icesjms/fsaf122){.doi target=_blank}

Serandour B, Blenckner T, ***Jan KMG***, Leroy B, Ramiro-Sánchez B, Campbell E, Winder M. 2024. [*Projections of spatial distributions of suitable environmental conditions for key Baltic Sea zooplankton species*]{.pubtitle}. Limnology and Oceanography **69**:12, 2801-2814. doi:[10.1002/lno.12705](https://doi.org/10.1002/lno.12705){.doi target=_blank}

***Jan KMG***, Serandour B, Walve J, Winder M. 2024. [*Plankton blooms over the annual cycle shape trophic interactions under climate change*]{.pubtitle}. Limnology and Oceanography Letters **9**:3, 209-218. doi: [10.1002/lol2.10385](https://doi.org/10.1002/lol2.10385){.doi target=_blank}

Novotny A, Serandour B, Kortsch S, Gauzens B, ***Jan KMG***, Winder M. 2023. [*DNA metabarcoding highlights cyanobacteria as the main source of primary production in a pelagic food web model*]{.pubtitle}. Science advances **9**:17, eadg1096. doi: [10.1126/sciadv.adg1096](https://doi.org/10.1126/sciadv.adg1096){.doi target=_blank}

Serandour B, ***Jan KMG***, Novotny A, Winder M. 2023. [*Opportunisitic vs selective feeding strategies of zooplankton under changing environmental conditions*]{.pubtitle}. Journal of Plankton Research **45**:2, 389-403. doi: [10.1093/plankt/fbad007](https://doi.org/10.1093/plankt/fbad007){.doi target=_blank}

Novotny A, ***Jan KMG***, Dierking J, Winder M. 2022. [*Niche partitioning between planktivorous fish in the pelagic Baltic Sea assessed by DNA metabarcoding, qPCR and microscopy*]{.pubtitle}. Scientific Reports **12**, 10952. doi: [10.1038/s41598-022-15116-7](https://doi.org/10.1038/s41598-022-15116-7){.doi target=_blank}


## Conférences

[**Swedish Oikos Meeting 2025** | Présentation orale [**Stockholm, Suède**]{.cvlocation}]{.cvcontainer} <br>
***Jan KMG***, Hentati-Sundberg J, Larson N, Winder M. [*Resource competition between small pelagic fish in the central Baltic Sea*]{.pubtitle}.

[**Marine Research Days 2024** | Présentation orale [**Kalmar, Suède**]{.cvlocation}]{.cvcontainer} <br>
***Jan KMG***, Hentati-Sundberg J, Larson N, Winder M. [*Are small pelagic fish competing for their resources in the central Baltic Sea?*]{.pubtitle}.

[**ICES Annual Science Conference 2024** | Poster [**Gateshead, Royaume-Uni**]{.cvlocation}]{.cvcontainer} <br>
***Jan KMG***, Hentati-Sundberg J, Larson N, Winder M. [*Implication of resource competition for forage fish dynamics in the central Baltic Sea*]{.pubtitle}.

[**Baltic Sea Science Congress 2023** | Présentation orale [**Helsinki, Finlande**]{.cvlocation}]{.cvcontainer} <br>
***Jan KMG***, Serandour B, Walve J, Winder M. [*Species-specific phenological responses to climate pose consequences for trophic coupling*]{.pubtitle}.

[**ASLO Aquatic Sciences Meeting 2023** | Poster [**Palma de Majorque, Espagne**]{.cvlocation}]{.cvcontainer} <br>
***Jan KMG***, Serandour B, Walve J, Winder M. [*Species-specific phenological responses to climate pose consequences for higher trophic levels*]{.pubtitle}.

[**Marine Research Days 2022** | Présentation orale [**Stockholm, Suède**]{.cvlocation}]{.cvcontainer} <br>
***Jan KMG***, Serandour B, Winder M. [*Coupling of plankton and small pelagic fish in the Baltic Sea*]{.pubtitle}.

[**18^th^ International Symposium on Microbial Ecology 2022** | Poster [**Lausanne, Suisse**]{.cvlocation}]{.cvcontainer} <br>
***Jan KMG***, Novotny A, Dierking J, Winder M. [*The role of eukaryotic microorganisms for niche partitioning of planktivorous fish*]{.pubtitle}.

[**Marine Research Days 2021** | Présentation orale [**Gothenburg, Suède**]{.cvlocation}]{.cvcontainer} <br>
***Jan KMG***. [*Copepod feeding preferences along the Baltic Sea environmental gradients - an assessment of zooplankton interactions using DNA metabarcoding*]{.pubtitle}.

## Services académiques

### Évaluations ponctuelles (reviews)

[Limnology and Oceanography Letters]{.pubtitle} <br>
[Molecular Ecology]{.pubtitle} <br>
[Marine Ecology Progress Series]{.pubtitle}