---
title: "PhD project"
toc: false
image: "image.svg"

listing:
  
  - id: SubProject
    grid-columns: 4
    max-description-length: 200
    image-height: 240px
    fields: [image, title, description]
    contents: 
      - Project1/*.qmd
      - Project2/*.qmd
      - Project3/*.qmd
      - Project4/*.qmd
    type: grid
    grid-item-border: false
    sort: false
---

My PhD thesis [**Resolving diversity and ecosystem functioning in a changing sea**](https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-249847){.button target=_blank} aims to answer the question: *How do the dynamics of plankton communities and their interactions with fish shape ecosystem functioning under changing environmental conditions?*

My PhD has been conducted at the [Department of Ecology, Environment and Plant Sciences, Stockholm University](https://www.su.se/department-of-ecology-environment-and-plant-sciences/){.button target=_blank} and was funded by [FORMAS](https://formas.se/en/start-page.html){.button target=_blank}.


**Abstract** <br>
Trophic interactions underpin ecosystem functioning by shaping energy flow within food webs. In marine systems, the high diversity of plankton forms a complex structure at the base of the food web that sustains small pelagic fish. Yet, trophic interactions are often inferred from coarse taxonomic or size-based assumptions, and the full spectrum of consumer diets is seldom resolved, limiting mechanistic understanding of ecosystem functioning. The primary objective of this thesis was to resolve the temporal dynamics of plankton and small pelagic fish, and their trophic interactions, to assess how ecosystem change alters food web topology and functioning. Using phenological indices derived from more than a decade of plankton monitoring, **Project I** revealed inconsistent trends across trophic levels, with the spring phytoplankton bloom occurring earlier, while zooplankton peak timings remained constant. This temporal mismatch had important ecological consequences, contributing to the decline of a key copepod species. To assess how alterations in species composition affect higher trophic levels, **Project II** applied DNA metabarcoding to characterise fish diets. By capturing the full dietary spectrum, this approach identified overlooked prey, including gelatinous and soft-bodied organisms. **Project III** applied DNA metabarcoding at larger scales, revealing limited diet overlap among the dominant small pelagic fish species, with prey availability and diversity identified as key factors shaping fish selectivity and resource use partitioning. Finally, **Project IV** combined decadal biomass observations and DNA inferred prey selectivity in a food web model to reconstruct energy flux from phytoplankton to fish at high taxonomic resolution, highlighting the role of diverse trophic interactions in shaping food web functioning. Together, these findings demonstrate the importance of assessing species dynamics across trophic levels at high temporal and taxonomic resolution to understand ecosystem functioning under changing environmental conditions. Moreover, this thesis illustrates that the diversity of trophic links, driven by species-specific traits, adds complexity to food web structure and contributes to the stability of energy transfer in marine systems.and help predict the variation of energy flow from primary producer to fish under different scenarios.

<hr class="about-sep">
::: {#SubProject}
:::
